name: TradeSystem
author: CodingAir
version: "${project.version}"
description: A beautiful way to trade with other players.
main: de.codingair.tradesystem.spigot.TradeSystem
softdepend: [Vault, Essentials, PlaceholderAPI, TokenManager, PlayerPoints, GriefDefender, MMOItems, WorldGuard, floodgate]
load-after: [Vault, Essentials, PlaceholderAPI, TokenManager, PlayerPoints, GriefDefender, MMOItems, WorldGuard, floodgate]

api-version: "1.13"

permissions:
  tradesystem.notify:
    default: op
  tradesystem.modify:
    default: op
  tradesystem.log:
    default: op
  tradesystem.trade:
    default: op
  tradesystem.trade.money:
    default: op
  tradesystem.trade.item:
    default: op
  tradesystem.trade.initiate:
    default: op
  tradesystem.*:
    children:
      tradesystem.notify: true
      tradesystem.modify: true
      tradesystem.log: true
      tradesystem.trade: true
      tradesystem.trade.item: true
      tradesystem.trade.money: true
      tradesystem.trade.initiate: true
